
name: ci

on:
  push:
  pull_request:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build -L
  check:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run checks
        run: nix develop -L --command pre-commit run --all-files

